<template>
    <div class="question_container">
        <head-top signin-up='home' head-title="客户协议" go-back='true'>
            <span slot='logo' class="head_logo"></span>
        </head-top>
        <section class="menu">
            <div class="qustion-item">
                <p class="title">Interactive Brokers LLC Customer Agreement 盈透证券有限公司客户协议</p>
                <p>1. Customer Agreement: This Agreement ("Agreement") governs the relationship between Customer and Interactive Brokers LLC ("IB"). If this Agreement varies from the IB website, this Agreement controls. This Agreement cannot be amended or waived except in writing by an IB officer. Customer Service employees cannot amend or waive any part of this Agreement. Customer acknowledges that IB may revise this Agreement by sending notice of the revised Agreement by e-mail or upon Customer log-in. Customer's use of IB after such notice constitutes acceptance of the revised Agreement.</p>
                <p>客户协议：本协议(以下简称为“协议” )用于管辖客户与盈透证券有限公司(以下简称为“盈透”)之间的关系。如本协议与盈透网站的内容有不一致之处，以本协议为准。除非经过盈透管理人员以书面形式提出，否则不可对本协议进行修改或放弃。客服人员不可修改或放弃本协议的任何部分。客户确认盈透可通过电子邮件发送修改协议通知或在客户登录后修改本协议。客户在上述通知后使用盈透服务被视为接受修改后的协议。</p>
                <p>2. No Investment, Tax or Trading Advice: IB representatives are not authorized to provide investment, tax or trading advice or to solicit orders. Nothing on IB's website is a recommendation or solicitation to buy or sell securities, futures or other investments.</p>
                <p>不提供投资、税务或交易建议：盈透代表未获授权提供投资、税务或交易建议或招揽定单。盈透网站上的任何内容均不可视为购买或出售证券、期货或其它投资产品的一种建议或招揽。</p>
                <p>3. Responsibility for Customer Orders/Trades: Customer acknowledges that IB does not know whether someone entering orders with Customer's user name/password is Customer. Unless IB is notified and agrees, Customer will not allow anyone to access Customer's account. Customer is responsible for the confidentiality and use of Customer's user name/password and agrees to report any theft/loss of such user name/password, or any unauthorized access to Customer's account, immediately by telephone or electronically through the IB website. Customer remains responsible for all transactions entered using Customer's user name/password.</p>
                <p>客户定单/交易责任：客户确认盈透并不知晓使用客户的用户名或密码输定单的人是否为客户本人。除非盈透公司已被告知并同意，否则客户应不允许任何人进入其账户。客户本人负责其用户名／密码的保密性与使用，并同意如上述用户名／密码被窃取或遗失或出现非法进入客户账户的情况，立即通过电话或通过盈透网站以电子方式报告。客户对使用其用户名／密码所进行的所有交易负责。</p>
                <p>4. Order Routing: Unless otherwise directed, IB will select the market/dealer to which to route Customer's orders. For products traded at multiple markets, IB may provide "Smart Routing", which seeks the best market for each order through a computerized algorithm. Customer should choose Smart Routing if available. If Customer directs orders to a particular market, Customer assumes responsibility for knowing and trading in accordance with the rules and policies of that market (e.g., trading hours, order types, etc.). IB cannot guarantee execution of every order at the best posted price: IB may not have access to every market/dealer; other orders may trade ahead; market centers may not honor posted prices or may re-route orders for manual handling; or market rules, decisions or system failures may prevent/delay execution of Customer's orders or cause orders not to receive the best price.</p>
                <p>定单传递：除非是直接传递，否则盈透将选择传递客户定单的市场／交易商。对于在多个市场交易的产品，盈透可能会提供“智能传递”手段，这一操作通过计算机算法为每个定单寻找最佳市场。在可用的情况下客户应选择智能传递。如客户将定单直接发送至一个特定的市场，则客户应承担知晓以及根据该市场的规定与政策进行交易的责任（如 交 易时间、定单类型等）。盈透不能保证所有定单均以最佳的公布价格执行，这是因为： 盈透可能不能进入所有市场／交易商；其它定单可能提前交易；市场中心可能不认可公布价或可能重新发送定单进行手工操作；或市场规则、决定或系统故障可能防止／ 延迟客户定单的执行或导致定单不能接收最佳价格。</p>
                <p>5. Order Cancellation/Modification: Customer acknowledges that it may not be possible to cancel/modify an order and that Customer is responsible for executions notwithstanding a cancel/modify request.</p>
                <p>定单取消/修改：客户确认可能无法取消／修改定单，并且尽管发出定单取消／修改要求，客户仍需对定单的执行结果负责。</p>
                <p>6. Order Execution: IB shall execute Customer orders as agent, unless otherwise confirmed. IB can execute Customer orders as principal. IB may use another broker, or an affiliate, to execute orders, and they have benefit of all IB's rights hereunder. IB may decline any Customer order, or terminate Customer's use of IB's services at any time in IB's discretion. All transactions are subject to rules and policies of relevant markets and clearinghouses, and applicable laws and regulations. IB IS NOT LIABLE FOR ANY ACTION OR DECISION OF ANY EXCHANGE, MARKET, DEALER, CLEARINGHOUSE OR REGULATOR.</p>
                <p>定单执行：除非由客户另外确认，否则盈透应作为代理执行客户定单。盈透可以作为执行客户定单的首要机构。盈透还可使用另一经纪商或一个分公司执行定单，且他们享有所有盈透的权利。盈透可自行决定拒绝任何客户定单或在任何时候终止客户使用盈透的服务。所有交易应遵守相关市场或清算机构的规定、政策及适用的法规。盈透对任何交易所、市场、交易商、清算机构或监管机构的任何行动或决定不承担责任。</p>
                <p>7. Confirmations:</p>
                <p>确认</p>
                <p>A. Customer agrees to monitor each order until IB confirms execution or cancellation. Customer acknowledges that confirmations of executions or cancellations may be delayed or may be erroneous (e.g. due to computer system issues) or may be cancelled/adjusted by an exchange. Customer is bound by the actual order execution, if consistent with Customer's order. If IB confirms execution or cancellation in error and Customer delays reporting such error, IB reserves the right to remove the trade from the account or require Customer to accept the trade, in IB's discretion.</p>
                <p>客户同意监视每个定单直至盈透确认执行或取消定单。客户知晓执行或取消的确认可能会被延误或可能发生错误（如由于计算机系统问题所引起）或可能被交易所取消／整。如实际执行的定单与客户的定单一致，客户应对实际执行的定单负责。如盈透确认执行或取消有错误，且客户延迟报告上述错误，则盈透保留从账户中取消这一交易或要求客户接受该交易的权利，具体由盈透自行决定。</p>
                <p>B. Customer agrees to notify IB immediately by telephone or electronically through the IB website if: i) Customer fails to receive an accurate confirmation of an execution or cancellation; ii) Customer receives a confirmation that is different than Customer's order; iii) Customer receives a confirmation for an order that Customer did not place; or iv) Customer receives an account statement, confirmation or other information reflecting inaccurate orders, trades, balances, positions, margin status or transaction history. Customer acknowledges that IB may adjust Customer's account to correct any error. Customer agrees to promptly return to IB any assets erroneously distributed to Customer.</p>
                <p>在以下情况下，客户同意立即通过电话或通过盈透的网站以电子方式通知盈透: i)客户未能收到定单被执行或被取消的准确确认; ii) 客户收到与客户定单不一致的确认; iii) 客户收到一份客户并未下达定单的确认;或iv)客户收到一个账户报告、确认或其它信息反映出不准确的定单、交易、余额、头寸、保证金状态或交易历史。客户确认盈透可能调整客户账户以更正任何错误。客户同意迅速将盈透由于失误分配给客户的任何资产返还给盈透。</p>
                <p>8. Proprietary Trading - Display of Customer Orders: Subject to all laws and regulations, Customer authorizes IB to execute proprietary trades of itself and its affiliates, though IB may simultaneously hold unexecuted Customer orders for the same products at the same price.</p>
                <p>自营交易–显示客户定单: 根据所有法律与法规的规定，客户授权盈透执行其与其分支机构的自营交易，虽然盈透可能对同一产品以同一价格同时持有未执行的客户定单。</p>
                <p>9. Customer Qualification: Customer warrants that his, her or its application is true and complete; will promptly notify IB of any information changes; and authorizes IB to make any inquiry to verify information.</p>
                <p>客户资质：客户需保证其申请资料的真实及完整性；如任何信息发生变化，将迅速通知盈透；客户还授权盈透公司进行任何调查以证实上述信息。</p>
                <p>A. Natural Persons: Customer warrants that Customer is over 18; is under no legal incapacity; and has sufficient knowledge and experience to understand the nature and risks of the products to be traded.</p>
                <p>自然人：客户保证已年满18周岁；具有所有法定资格；具有足够的知识与经验理解将要交易的产品的性质与风险。</p>
                <p>B. Organizations: Customer and its authorized representatives warrant that Customer: (i) is authorized under its governing document(s) and in the jurisdictions in which it is organized and/or regulated to enter this Agreement and trade (including on margin if applicable); (ii) is under no legal incapacity; and (iii) that persons identified to enter orders have proper authority and have sufficient knowledge and experience to understand the nature and risks of the products to be traded.</p>
                <p>组织：客户与其授权代表保证，客户:(i)根据其组织文件和其所组建和／或受监管的管辖地内获得授权签署本合同与交易（如适用的话，包括保证金交易）;(ii)具有所有法律资格; 且(iii)确认输入定单的人员具有适当的授权且具有足够的知识与经验理解其所将要交易的产品的性质与风险。</p>
                <p>C. Trusts: "Customer" refers to the Trust and/or Trustees. Trustee(s) represent(s) that there are no Trustees other than listed in the application and certifies(y) that IB may follow instructions from any Trustee and deliver funds, securities, or any other assets to any Trustee or on any Trustee's instructions, including delivering assets to a Trustee personally. IB, in its discretion, may require written consent of any or all Trustee(s) prior to following instructions of any Trustee. Trustee(s) certify that Trustee(s) has (have) the power under the Trust documents and applicable law to enter this Agreement, open the type of account applied for, and enter transactions and issue instructions. Such powers include, without limit, authority to buy, sell (including short), exchange, convert, tender, redeem and withdraw assets (including delivery of securities to/from the account) to trade securities on margin or otherwise (including purchase/sale of options), and trade futures and/or options on futures, for the Trust. Should only one Trustee execute this Agreement, Trustee represents that Trustee has the authority to execute this Agreement, without consent by the other Trustees. Trustee(s) certifies(y) that all transactions for this account will comply with the Trust documents and applicable law and that all trading in this Account will be consistent with the powers delegated to the Trustee(s) by the Trust document(s) and with the fiduciary duties of the Trustee(s) to the Trust and/or the beneficiary(ies) of the Trust. Trustee(s) also certifies(y) that Trustee(s) will inform any beneficiary(ies) of the Trust of the activity in the Trust's account(s) as required by the Trust document and applicable law. Trustee(s), jointly and severally, shall indemnify IB and hold IB harmless from any claim, loss, expense or liability for effecting any transactions, and acting upon any instructions given by the Trustee(s). Trustee(s) will notify Interactive promptly if the authority of the Trustee(s) change in any manner material to this Agreement, including but not limited to any change affecting the accuracy of any warrants made herein. </p>
                <p>信托：“客户”指的是信托人和／或受托人。受托人表示除了列明在申请资料上的受托人以外没有其他的受托人，并证实盈透可遵从任何受托人的指示，将资金、证券或任何它资产交付给任何受托人或根据任何受托人的指示将资金、证券或任何其它资产交付给任何受托人，包括将资产交付给受托人本人。盈透可自行决定要求在遵从任何受托人的指示前获得任何或所有受托人的书面同意。根据信托文件和现行法律，受托人有权签署本合同打开所申请的账户类型、进行交易及发布指令。上述权力包括但不限于由信托授权买入、卖出（包括卖空）、交易、转换、偿还、赎回与提取资产（包括向／从账户内交付证券）、 授权以保证金交易证券或与此相反（包括购买／出售期权）、交易期货和／或交易期货期 权。如只有一名受托人执行本合同，受托人表示无需获得其它受托人同意的情况下其有权执行本合同。受托人证明本账户的所有交易将遵守信托文件与适用法律。受托人应共同并各自保障盈透公司免于承担根据受托人指示采取的任何交易和行动所引起的任何索赔、损失、费用或责任。</p>
                <p>D. Regulated Persons and Entities: Unless Customer notifies IB otherwise, Customer represents that Customer is not a broker-dealer; futures commission merchant; or affiliate, associated person or employee thereof. Customer agrees to notify IB immediately by telephone or electronically through the IB website if Customer becomes employed or associated with a broker-dealer or futures commission merchant.</p>
                <p>受监管的个体或实体：除非客户通知盈透，否则客户表示他不是一名经纪商-交易商、期货佣金商、或其分支机构、关联人士或雇员。如果客户成为一个经纪商-交易商或期货佣金商的雇员或与之相关联，客户同意立即通过电话或通过盈透的网站以电子方式通知透。</p>
                <p>10. Joint Accounts: Each joint account holder agrees that each joint holder has authority, without notice to the other, to: (i) buy/sell securities, futures or other products (including on margin); (ii) receive account confirmations and correspondence; (iii) receive and dispose of money, securities or other assets; (iv) enter, terminate, or agree to modify this Agreement; (v) waive any part of this Agreement; and (vi) deal with IB as if each joint holder was the sole holder. Notice to any joint holder constitutes notice to all joint holders. Each joint account holder is jointly andseverally liable to IB for all account matters. IB may follow instructions of any joint holder and make delivery to any joint account holder individually of any account property.</p>
                <p>联名账户：每个联名账户的持有人同意每位联名持有人在不通知其它持有人的情况下有权：(i)买／卖证券、期货或其它产品（包括保证金交易）；(ii)接收账户确认与函件；(iii) 接收与处理钱款、证券或其它资产；(iv) 签署、终止或同意修改本合同；(v)放弃本合同的任何部分；和(vi)如每个联名持有人为单独的持有人与盈透进行交道。发给任何联名持有人的通知视为发给所有联名持有人的通知。每个联名账户持有人共同并各自向盈透负责所有账户事宜。盈透可遵从任何一位联名持有人的指示，并可将任何账户财产单独交付给任何账户持有人。</p>
                <p>Upon death of any joint holder, the surviving holder shall give IB notice by telephone or electronically through the IB website and IB may, before or after notice, initiate proceedings, require documents, retain assets and/or restrict transactions as it deems advisable to protect itself against any liability or loss. The estate of any deceased joint account holder shall be liable and each survivor will be liable, jointly and severally, to IB for any debt or loss in the account or upon liquidation of the account. Unless Customers indicate otherwise, IB may presume that account holders are joint tenants with rights of survivorship. Upon death of any joint holder, the account shall be vested in the surviving holders, without in any manner releasing the deceased joint holder's estate from liability.</p>
                <p>在任何联名持有人已故后，幸存的持有人应通过电话或通过盈透网站以电子方式通知盈透，盈透可在通知前或通知后，发起诉讼、要求提交文件、保留资金和／或采取其所认为适当的措施限制交易以保护其自身免于任何责任或损失。任何已故联名账户持有人的遗产与每位幸存的联名账户持有人将共同并各自向盈透公司负责赔偿账户内的或账户清算后的任何债务或损失。除非客户另有说明，否则盈透可认为账户持有人是共同财产占有人，对共有财产中死者权利部分享有权利。在任何联名账户持有人死亡后，账户应被授予给幸存的持有人，同时不得以任何方式使死亡的联名持有人的遗产免于承担责任。</p>
                <p> 11. Margin:</p>
                <p> 保证金：</p>
                <p> A. Risk of Margin Trading: Margin trading is highly risky and may result in a loss of funds greater than Customer has deposited in the account. Customer represents that he or she has read the "Disclosure of Risks of Margin Trading" provided separately by IB.</p>
                <p> 保证金交易的风险：保证金交易具有高风险性，导致的损失可能超过客户账户内的已存资金。客户表示已阅读由盈透公司单独提供的“保证金交易风险披露书” 。</p>
                <p> B. Requirement to Maintain Sufficient Margin Continuously: Margin transactions are subject to initial and maintenance margin requirements of exchanges, clearinghouses and regulators and also to any additional margin requirement of IB, which may be greater ("Margin Requirements"). IB MAY MODIFY MARGIN REQUIREMENTS FOR ANY OR ALL CUSTOMERS FOR ANY OPEN OR NEW POSITIONS AT ANY TIME, IN IB'S SOLE DISCRETION. Customer shall monitor his, her or its account so that at all times the account contains sufficient equity to meet Margin Requirements. IB may reject any order if the account has insufficient equity to meet Margin Requirements, and may delay processing any order while determining margin status. Customer shall maintain, without notice or demand, sufficient equity at all times to continuously meet Margin Requirements. Formulas for calculating Margin Requirements on the IB website are indicative only and may not reflect actual Margin Requirements. Customer must at all times satisfy whatever Margin Requirement is calculated by IB.</p>
                <p>要求连续维持足够保证金：保证金交易应遵守交易所、清算机构、监管机构的初始保证 金与维持保证金的要求，同样还应遵守盈透的任何附加保证金规定，盈透的保证金的金额可能会更高(“保证金要求”)。盈透可自行决定在任何时间对任何开仓或新头寸修改任何或所有客户的保证金要求。客户应监控其账户以保证在任何时候账户均持有的足够的股权满足保证金要求。如账户内的股权不足以达到保证金要求，则盈透可拒绝任何定单，且可在确定保证金状态时延迟处理任何定单。无需任何通知或要求，客户应在任何时候保持足够的股权以持续满足保证金要求。盈透网站上用的保证金计算公式仅作参考，可能不能反映出实际的保证金要求。客户必须在任何时候满足由盈透计算的保证金要求。</p>
                <p> C. IB Will Not Issue Margin Calls: IB does not have to notify Customer of any failure to meet Margin Requirements prior to IB exercising its rights under this Agreement. Customer acknowledges that IB generally will not issue margin calls; generally will not credit Customer's account to meet intraday or overnight margin deficiencies; and is authorized to liquidate account positions in order to satisfy Margin Requirements without prior notice.</p>
                <p>盈透将不发出追加保证金通知：盈透在根据本合同行使其权利前不一定非得通知客户其未能达到保证金要求。客户确认盈透一般不会发出追加保证金的通知；一般来说将不会信客户账户补足日内或隔夜保证金短缺；且在不事先通知的情况下有权利平仓账户头寸以满足保证金要求。</p>
                <p> D. Liquidation of Positions and Offsetting Transactions:</p>
                <p>清算头寸与抵消交易：</p>
                <p> i. IF AT ANY TIME CUSTOMER'S ACCOUNT HAS INSUFFICIENT EQUITY TO MEET MARGIN REQUIREMENTS OR IS IN DEFICIT, IB HAS THE RIGHT, IN ITS SOLE DISCRETION, BUT NOT THE OBLIGATION, TO LIQUIDATE ALL OR ANY PART OF CUSTOMER'S POSITIONS IN ANY OF CUSTOMER'S IB NON-IRA ACCOUNTS, INDIVIDUAL OR JOINT, AT ANY TIME AND IN ANY MANNER AND THROUGH ANY MARKET OR DEALER, WITHOUT PRIOR NOTICE OR MARGIN CALL TO CUSTOMER. CUSTOMER SHALL BE LIABLE AND WILL PROMPTLY PAY IB FOR ANY DEFICIENCIES IN CUSTOMER'S ACCOUNT THAT ARISE FROM SUCH LIQUIDATION OR REMAIN AFTER SUCH LIQUIDATION. IB HAS NO LIABILITY FOR ANY LOSS SUSTAINED BY CUSTOMER IN CONNECTION WITH SUCH LIQUIDATIONS (OR IF THE IB SYSTEM DELAYS EFFECTING, OR DOES NOT EFFECT, SUCH LIQUIDATIONS) EVEN IF CUSTOMER RE-ESTABLISHES ITS POSITION AT A WORSE PRICE.</p>
                <p>如在任何时候，客户账户中的股权不足以满足保证金要求或为亏缺，则盈透有权自行决定但并非有此义务，在任何时候以任何方式、通过任何市场或交易商，在无事先通知或向客户发出追加保证金通知的情况下，清算在任何客户的盈透账户内所 有或任何部分客户头寸（无论是个人的账户或联名账户）。客户应负责且将迅速向 盈透支付由于上述平仓或上述平仓后保留的头寸所引起的客户账户账面所短少的金额。盈透对与上述平仓有关的客户所遭受的任何损失均不负有责任（或如盈透系统 延迟执行或未能执行上述平仓）即便客户在一个更差的价格重建其仓位。</p>
                <p> ii. IB may allow Customer to pre-request the order of liquidation in event of a margin deficiency, but such requests are not binding on IB and IB retains sole discretion to determine the assets to be liquidated and the order/manner of liquidation. IB may liquidate through any market or dealer, and IB or its affiliates may take the other side of the transactions consistent with laws and regulations. If IB liquidates any/all positions in Customer's account, such liquidation shall establish Customer's gain/loss and remaining indebtedness to IB, if any. Customer shall reimburse and hold IB harmless for all actions, omissions, costs, fees (including, but not limited to, attorney's fees), or liabilities associated with any such transaction undertaken by IB. If IB executes an order for which Customer did not have sufficient equity, IB has the right, without notice, to liquidate the trade and Customer shall be responsible for any resulting loss and shall not be entitled to any resulting profit.</p>
                <p>如出现保证金不足的情况，盈透公司可允许客户预先要求清算顺序，但上述要求对盈透公司不具有约束力，盈透公司有权独自确定要清算的资产、清算顺序及清算方式。盈透可通过任何市场或交易商进行清算，盈透或其分支机构可能按符合法律 法规的情况下做为交易的另一方。如盈透清算客户账户中的任何／所有仓位，上述 清算仓位应确定客户的收益／损失与所欠盈透的债务，如有的话。客户应对由盈透 所承担的任何上述交易相关的所有 诉讼、疏忽、成本与费用（包括但不限于律师费）或责任做出补偿或使之不受损害。如盈 透公司在客户账户内无足够的股权时执 行一个定单，盈透有权在不事先通知客户的情况下清算交易，且客户应对任何由此引起的损失负责，且没 有权利获得任何由此所得的利润。</p>
                <p> iii. If IB does not, for any reason, liquidate under-margined positions, and issues a margin call, Customer must satisfy such call immediately by depositing funds. Customer acknowledges that even if a call is issued, IB still may liquidate positions at any time.</p>
                <p>无论出于何种原因，如果盈透未能清算保证金不足的头寸且发出追加保证金通知，客户必须立即存入资金满足上述保证金追缴通知。客户确认如发出追缴通知后，盈透仍可在任何时候平仓头寸。</p>
                <p> iv. Customer acknowledges that IB also has the right to liquidate all or part of Customer's positions without prior notice: (i) if any dispute arises concerning any Customer trade, (ii) upon any "Default" as described in 16 below, or (iii) whenever IB deems liquidation necessary or advisable for IB's protection.</p>
                <p>客户确认盈透同样还有权在没有事先通知时清算所有或部分客户的仓位：(i)如在客户的任何交易出现任何争议时，(ii)出现在以下第16条中所述的任何“违约”后，或 (iii)任何时候当盈透认为为了保护盈透的利益有必要或适当地进行清算时。</p>
                <p> 12. Universal Accounts: An IB Universal Account is two underlying accounts: an SEC-regulated securities account and a CFTC-regulated commodity account. Customer authorizes transfers between the securities and commodity accounts to cover Margin Requirements and other obligations, and acknowledges IB may liquidate positions to cover obligations in the other account. Customer authorizes IB to provide combined confirmations/statements for both accounts. Customer acknowledges that only assets in the securities account are covered by SIPC protection and excess coverage and not assets in the commodity account.</p>
                <p>全能账户：一个盈透全能账户为两个基础账户,其中一个是美国证券交易委员会 (SEC)监 管的证券账户，另一个是美国商品期货交易委员会(CFTC)监管的商品账户。客户授权在证券与商品账户之间进行转账以满足保证金要求与其它债务要求并确认盈透可平仓以支付其它账户内的债务。客户授权盈透为上述账户提供合并确认书／报表。客户确认仅证券账户内的资产受到美国证券投资者保护基金(SIPC)的保护或者额外保护，但不包括商品账户内的资产。</p>
                <p> 13. Short Sales: Customer acknowledges that short sales must be done in a margin account, subject to Margin Requirements; that prior to selling short, IB must believe it can borrow stock for delivery; and that if IB cannot borrow stock (or re-borrow after a recall notice) IB may buy-in stock on Customer's behalf, without notice to Customer, to cover short positions and Customer is liable for any losses/costs.</p>
                <p>卖空：客户确认卖空必须在保证金账户内进行，并符合保证金的要求；在卖空前，盈透必须确信其能借入股票进行交付；且如盈透不能借入股票（或在召回通知发出后再次借用），盈透可在不通知客户的情况下以客户名义买入股票以补仓，客户对此所引发的任何损失／费用负责。</p>
                <p> 14. IB's Right to Loan/Pledge Customer Assets: As allowed by law, IB is authorized by Customer to lend to itself or others Customer securities or assets. IB may, without notice, pledge, re-pledge, hypothecate or re-hypothecate Customer's securities and assets, separately or together with those of other customers, for any amount due in any IB account in which Customer has an interest, without retaining in IB's possession or control a like amount of assets. For loans of securities, IB may receive financial and other benefits to which Customer is not entitled. Such loans could limit Customer's ability to exercise securities' voting rights.</p>
                <p>盈透借贷/质押客户资产的权利： 根据法律规定允许的范围，客户授权盈透可以向其或其它客户借出证券或资产。无需通知客户，IB可对客户在盈透账户中有股权的任何到期金额单独或与其它客户一起质押、再质押、抵押或再抵押客户的证券与资金，而盈透不必保持对一项相同资产的拥有或控制权。对于证券的借贷，盈透可接受客户无权享有的经济利益与其它利益。该等借贷可能会限制客户行使证券表决权的能力。</p>
                <p> 15. Security Interest: All assets of any kind held by or on behalf of IB for Customer's account are hereby pledged to IB and are subject to a perfected first priority lien and security interest in IB's favor to secure performance of obligations and liabilities to IB arising under this or any other Agreement.</p>
                <p>担保权益：由盈透所持有的或代表盈透的客户账户的所有客户资产在此质押给盈透，且盈透对留置与担保权益应享有完全优先受偿的权利，以确保本合同或任何其它合同项下的所欠下的盈透的债务与欠债得以清偿。</p>
                <p> 16. Event of Default: A "Default" occurs automatically, without notice upon: (i) Customer breach/repudiation of any agreement with IB; (ii) Customer failure to provide assurance satisfactory to IB of performance of an obligation, after request from IB in IB's sole discretion; (iii) proceedings by/against Customer under any bankruptcy, insolvency, or similar law; (iv) assignment for the benefit of Customer's creditors; (v) appointment of a receiver, trustee, liquidator or similar officer for Customer or Customer property; (vi) Customer representations being untrue or misleading when made or later becoming untrue; (vii) legal incompetence of Customer; (viii) proceeding to suspend Customer's business or license by any regulator or organization; (ix) IB having reason to believe that any of the foregoing is likely to occur imminently.</p>
                <p>违约事件：在不通知的情况下，“违约”在以下情况下自动发生：(i)客户违反／拒绝履行与盈透之间的任何合同；(ii)在盈透自行决定发出要求后，客户未向盈透提供让盈透满意的清偿债务保证；(iii) 根据任何破产法或相似的法律，由客户发起或针对客户发起诉讼；(iv)为了客户债权人的利益进行转让；(v)指定客户或客户财产的接 收 人、受托人、财产清算人或类似人员；(vi)客户的陈述在当时进行时不真实或具有误导性，或后来不具有真实性；(vii)客户无法律行为能力；(viii)由任何监管机构或组织终止客户业务或许可；(ix)盈透有理由相信任何以上情况可能即将发生。</p>
                <p>Customer unconditionally agrees that, upon a Default, IB may terminate any or all IB's obligations to Customer and IB shall have the right in its discretion, but not the obligation, without prior notice, to liquidate all or any part of Customer's positions in any IB account, individual or joint, at any time and any manner and through any market or dealer. Customer shall reimburse and hold IB harmless for all actions, omissions, costs, fees (including, but not limited to, attorney's fees), or liabilities associated with any Customer Default or any transaction undertaken by IB upon Default.</p>
                <p>客户无条件同意一旦违约，盈透可终止履行其对客户的部分或所有义务，且盈透有权自行决定但并非有此义务在无事先告知的情况下，在任何时间以任何方式通过任何市场或交易商清算任何盈透个人账户或联名账户内所有或部分客户的仓位。客户应对任何客户违约相关的、或者因客户违约由盈透完成的交易相关的所有诉讼、疏忽、成本与费用（包括但不 限于律师费）或债务做出补偿或使之不受损害。</p>
                <p> 17. Suspicious Activity: If IB in its sole discretion believes that a Customer account has been involved in any fraud or crime or violation of laws or regulations, or has been accessed unlawfully, or is otherwise involved in any suspicious activity (whether victim or perpetrator or otherwise), IB may suspend or freeze the account or any privileges of the account, may freeze or liquidate funds or assets, or may utilize any of the remedies in this Agreement for a "Default".</p>
                <p>可疑行为：如盈透根据其自已的判断认为客户的账户参与了任何诈欺或犯罪行为，或违反法律法规，或已被非法侵入或卷入任何可疑行为（无论是作为受害者或犯罪者或其它身份），盈透可终止或冻结账户、或账户的任何特权；可冻结或清算资金或资产；或可利用本合同的“违约事件”的任何法律补偿。</p>
                <p> 18. Multi-Currency Function in IB Accounts:</p>
                <p>盈透账户内的多币种功能：</p>
                <p> A. Customers may be able to trade products denominated in different currencies using a base currency chosen by Customer. Upon purchase of a product denominated in a different currency from the base currency, a margin loan is created to fund the purchase, secured by the assets in Customer's accounts. If Customer maintains positions denominated in foreign currencies, IB will calculate Margin Requirements by applying exchange rates specified by IB. IB WILL APPLY "HAIRCUTS" (A PERCENTAGE DISCOUNT ON THE FOREIGN CURRENCY EQUITY AMOUNT) TO REFLECT THE POSSIBILITY OF FLUCTUATING EXCHANGE RATES BETWEEN THE BASE CURRENCY AND THE FOREIGN CURRENCY. CUSTOMER MUST CLOSELY MONITOR MARGIN REQUIREMENTS AT ALL TIMES, PARTICULARLY FOR POSITIONS DENOMINATED IN FOREIGN CURRENCIES, BECAUSE FLUCTUATION IN THE CURRENCY ANDTHE VALUE OF THE UNDERLYING POSITION CAN CAUSE A MARGIN DEFICIT.</p>
                <p>客户可使用一个由客户选定的基础货币对以不同货币计价的产品进行交易。在购买与基础货币不同的计价货币产品时，创建了为购买产品提供资金的保证金，并由客户账户内的资金提供担保。如客户保持以外币计价的头寸，盈透将利用由其指定的汇率，计算保证金要求。盈透将利用“折扣”基于外币的股权额的一个百分比折扣率)以反映基础货币与该外币之间的波动汇率的可能性。客户必须随时密切监视保证金要求，特别是以外币计价的头寸的保证金要求。因为该货币与底层证券头寸价值的波动可能引起保证金不足。</p>
                <p> B. Customer agrees that IB’s obligations to Customer shall be denominated in: (i) the United States dollar; (ii) a currency in which funds were deposited by Customer or were converted at the request of Customer, to the extent of such deposits and conversions; or (iii) a currency in which funds have accrued to the customer as a result of trading conducted on a designated contract market or registered derivatives transaction execution facility, to the extent of such accruals. Information regarding Customer’s currency conversions is provided on the IB customer statements. Customer further agrees that IB may hold customer funds in: (i) the United States; (ii) a money center country as defined by the US Commodity Exchange Act & regulations thereunder; or (iii) the country of origin of the currency. In addition, Customer acknowledges and authorizes IB to hold Customer’s funds outside the United States, in a jurisdiction that is neither a money center country nor the country of origin of the currency in order to facilitate Customer’s trading in investments denominated in that currency.</p>
                <p>客户同意盈透对其应尽义务范围按以下所列货币项目为基准进行界定：(i)美元；(ii) 客户存入基金的货币或要求转换的货币，包括客户所存放的资金和所转换成的货币的额度；或 (iii)客户通过在特定的合约市场进行交易所产生的基金货币，或是客户通过合法衍生性商品交易市场投资获利产生的货币。客户货币转换的相关资讯详载于盈透客户声中。此外，客户同意在下列地点条件下，盈透可以持管其资金：(i)美国；(ii) 美国商品交易 法及其相关规定所认可的货币中心国家境内；或 (iii) 该币种的原属国家境内。此外，客户认可同意并授权盈透可以在美国境外持管其资金，以方便盈透能在美国境外用当地的货币来协助客户进行交易投资，上述所称的美国境外，是指货币交易中心或货币原属国以外的地区，其司法管辖权不属美国。</p>
                <p> 19. Foreign Currency Exchange ("Forex") Transactions:</p>
                <p>外币兑换（简称“外汇交易”）：</p>
                <p> A. HIGH RISKS OF FOREX TRADING: FOREX TRADING IS GENERALLY UNREGULATED, IS HIGHLY RISKY DUE TO THE LEVERAGE (MARGIN) INVOLVED, AND MAY RESULT IN LOSS OF FUNDS GREATER THAN CUSTOMER DEPOSITED IN THE ACCOUNT. Customer represents that he or she has read and acknowledges the "Risk Disclosure Statement for Forex Trading and Multi-Currency Accounts" provided separately by IB.</p>
                <p>外汇交易的高风险性：外汇交易一般不受监管，由于牵涉到杠杆（保证金）， 具有高风险性，且所引起的资金损失可能超过账户内客户所存的资金。客户确认盈透公司单独提供的“外汇交易与多币种账户风险披露声明”。</p>
                <p> B. For Forex transactions, IB generally will act as agent or riskless principal and charge a fee. IB may effect Forex transactions through an affiliate or third party, which may profit or lose from such transactions. Customer agrees that IB may transfer to or from Customer's regulated futures or securities account(s) from or to any of Customer's non-regulated Forex account any funds or assets that may be required to avoid margin calls, reduce debit balances or for any other lawful reason.</p>
                <p>对于外汇交易，盈透通常作为一个代理人或无风险主体，收取手续费。盈透可通过其分支机构或第三方进行外汇兑换交易，上述分支机构或第三方可从上述交易中获得收益或承担损失。客户同意盈透可将任何资金或资产转出或转入客户的受监管的期货或证券账户、转入或转出客户的任何非监管外汇账户，以便避免保证金追缴通知、减少借方余额或为了任何其它合法理由。</p>
                <p> C. Netting: (i) Netting by Novation. Each Forex transaction between Customer and IB will immediately be netted with all then-existing Forex transactions between Customer and IB for the same currencies to constitute one transaction. (ii) Payment Netting. If on any delivery date more than one delivery of a currency is due, each party shall aggregate the amounts deliverable and only the difference shall be delivered. (iii) Close-Out Netting. If Customer: (a) incurs a margin deficit in any IB account, (b) defaults on any obligation to IB, (c) becomes subject to bankruptcy, insolvency or other similar proceedings, or (d) fails to pay debts when due, IB has the right but not the obligation to close out Customer's Forex transactions, liquidate all or some of Customer's collateral and apply the proceeds to any debt to IB. (iv) Upon Close-Out Netting or any "Default", all outstanding Forex transactions will be deemed terminated as of the time immediately preceding the triggering event, petition or proceeding. (v) IB's rights herein are in addition to any other rights IB has (whether by agreement, by law or otherwise).</p>
                <p>净额结算：(i)通知债务更新进行净额结算。客户与盈透之间的每笔外汇兑换交 易将立 即以相同的币种进行客户与盈透之间的所有现有外汇兑换交易进行净额结算以构成一次 交易。(ii)支付净额结算。如在任何一个交割日期，有一种货币的多个到期进行交割，则每一方应计算应交割的总金额，只进行差额的交割。(iii)终止型净额结算。如客户：(a)在 任何盈透的账户内出现保证金短缺；(b)在任何对盈透的义务方面违约，(c)进入破产或其它相似程序，或(d)未能支付到期债务，则盈透有权但无此义务终止客户外汇兑换交易、清算所有或部分客户的担保品并将所得用于 支付所欠盈透的任何债务。(iv)在终止型净额 清算或任何“违约”后，所有未执行的 外汇兑换交易将视为在触发事件、请愿或诉讼前即 已终止。(v)盈透的权利附加在 盈透拥有的任何其它权利上（无论是合同、法律等所赋予 的权利）。</p>
                <p> D. Nothing herein constitutes a commitment of IB to offer Forex transactions generally or to enter into any specific Forex transaction. IB reserves the unlimited right to refuse any Forex order or to decline to quote a two-way market in any currency.</p>
                <p>本合同中任何内容不得视为盈透承诺提供一般的外汇兑换交易或签署任何特定的外汇兑换交易。盈透保留不受限制拒绝任何外汇兑换交易定单或拒绝以任何货币进行双向市场报价的权力。</p>
                <p> 20. Commodity Options and Futures Not Settled in Cash: Customer acknowledges that: (A) commodity options cannot be exercised and must be closed out by offset; and (B) for futures contracts that settle not in cash but byphysical delivery of the commodity (including currencies not on IB's Deliverable Currency List), Customer cannot make or receive delivery. If Customer has not offset a commodity option or physical delivery futures position prior to the deadline on the IB website, IB is authorized to roll or liquidate the position or liquidate any position or commodity resulting from the option or futures contract, and Customer is liable for all losses/costs.</p>
                <p>不以现金结算的商品期权与期货：客户确认：(A)商品期权不能行使，必须通过对冲来平仓；且(B) 对于不以现金结算而通过商品实物交割的期货合约（包括不在盈透可交割货币清单上的货币），客户不能进行或接受交割。如客户在盈透网站上公布的最后截止日期前尚未抵销商品期权或实物交割期货仓位，客户授权盈透转仓或平仓或清算由期权或期货合约所引起的任何仓位或商品，客户负责承担所有损失/费用。</p>
                <p> 21. Commissions and Fees, Interest Charges, Funds: Commissions and fees are as specified on the IB website unless otherwise agreed in writing by an officer of IB. Customer acknowledges that IB deducts commissions/fees from Customer accounts, which will reduce account equity. Positions will be liquidated if commissions or other charges cause a margin deficiency. Changes to commissions/fees are effective immediately upon either of: posting on the IB website or email or other written notice to Customer. IB shall pay credit interest to and charge debit interest from Customer at interest rates and terms on the IB website. Customer funds will not be disbursed until after transactions are settled. Terms and conditions for deposit and withdrawal of funds (including holding periods) are as specified on the IB website.</p>
                <p>佣金与手续费、利息费用、资金：除非盈透管理人员书面同意，否则佣金与手续费按照盈透网站上确定的收取。客户确认盈透从客户账户扣除佣金／手续费，由此将降低账户的股权。如佣金或其它收费引起保证金出现短缺，将平仓头寸。在以下任何一种情况发生后佣金或手续费变化即生效：登在盈透网站上或以电子邮件或其它书面通知发送给客户。盈透应以其网站上载明的利率与条款向客户支付利息收入，向客户收取借项利息。客户资金只有在交易结算后方可拨付。资金存入与支取条款（包括持有时间）在盈透网站上具体规定。</p>
                <p> 22. Account Deficits: If a cash account incurs a deficit, margin interest rates will apply until the balance is repaid, and IB has the right, but not the obligation, to treat the account as a margin account. Customer agrees to pay reasonable costs of collection for any unpaid Customer deficit, including attorneys' and collection agent fees.</p>
                <p>账户负结余：如一个现金账户出现负值，将对差额实行保证金利率直到偿还为止，盈透有权但无义务将此账户作为保证金账户对待。客户同意对任何未支付的客户帐户不足资金支付合理的收款成本，包括律师费与收款代理人手续费。</p>
                <p> 23. Risks of Foreign Markets; After Hours Trading: Customer acknowledges that trading securities, options, futures, currencies or any product on a foreign market is speculative and involves high risk. There also are special risks of trading outside ordinary market hours, including risk of lower liquidity, higher volatility, changing prices, un-linked markets, news announcements affecting prices and wider spreads. Customer represents that Customer is knowledgeable and able to assume these risks.</p>
                <p>外国市场的风险；收盘后交易时段的风险： 客户确认在外国市场上进行证券、期权、期 货、货币或任何产品的交易具有投机性，存在很高的风险。还存在正常交易时间以外的特殊交易风险，包括低流动性风险、高波动率的风险，价格变化风险、未能连接的市场，影响价格的新闻公告与更大差价。客户表示其充分了解上述风险，且有能力承担上述风险。</p>
                <p> 24. Knowledge of Securities, Warrants and Options; Corporate Actions: Customer acknowledges Customer's responsibility for knowing the terms of any securities, options, warrants or other products in Customer's account, including upcoming corporate actions (e.g., tender offers, reorganizations, stock splits, etc.). IB has no obligation to notify Customer of deadlines or required actions or dates of meetings, nor is IB obligated to take any action without specific written instructions sent by Customer to IB electronically through the IB website.</p>
                <p> 证券、权证与期权的知识；公司活动：客户确认客户有责任了解客户账户内任何证券、 期权、权证或其它产品的条款，包括即将发生的公司活动(如股权收购要约、重组与股票分割等)。盈透无义务通知客户截止时间或所需要采取的行动或会议日期，在客户没有通过盈透网站以电子形式发出具体书面指示给盈透的情况下盈透也无义务采取任何行动。</p>
                <p> 25. Quotes, Market Information, Research and Internet Links: Quotes, news, research and information accessible through IB (including through links to outside websites) ("Information") may be prepared by independent Providers. The Information is the property of IB, the Providers or their licensors and is protected by law. Customer agrees not to reproduce, distribute, sell or commercially exploit the Information in any manner without written consent of IB or the Providers. IB reserves the right to terminate access to the Information. None of the Information constitutes a recommendation by IB or a solicitation to buy or sell. Neither IB nor the Providers guarantee accuracy, timeliness, or completeness of the Information, and Customer should consult an advisor before making investment decisions. RELIANCE ON QUOTES, DATA OR OTHER INFORMATION IS AT CUSTOMER'S OWN RISK. IN NO EVENT WILL IB OR THE PROVIDERS BE LIABLE FOR CONSEQUENTIAL, INCIDENTAL, SPECIAL OR INDIRECT DAMAGES ARISING FROM USE OF THE INFORMATION. THERE IS NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, REGARDING THE INFORMATION, INCLUDING WARRANTY OF MERCHANTIBILITY, WARRANTY OF FITNESS FOR A PARTICULAR USE OR WARRANTY OF NON-INFRINGEMENT.</p>
                <p>报价、市场信息、研究与网络连接：通过盈透（包括通过连接到外部网站可访问的报价、新闻、研究与信息（“信息”）可由独立的提供商编制。上述信息是盈透、 提供商或其许可方的财产，受法律保护。客户同意如无盈透或提供商的书面同意不会复制、分发、出售或以任何方式将信息用于商业目的。盈透保有终止访问上述信息的权利。信息 中的任何内容均不可视为盈透的推荐或买卖诱导。盈透与提供商均不保证本信息的准确性、及时性或完整性，客户在做出投资决策前应向顾问进行咨询。客户信赖报价、数据 或其它信息，风险自负。在任何情况下盈透或提供商对使用上述信息所引起的偶然的、 特殊的或间接的损害后果均不负有任何责任。不提供任何形式的担保，无论是与信息有关的明示还是暗含的、包括适销性担保、对一种特定的用途适应性的担保或非侵权担 保。</p>
                <p> 26. License to Use IB Software: IB grants Customer a non-exclusive, non-transferable license to use IB Software solely as provided herein. Title to IB Software and updates shall remain the sole property of IB, including all patents, copyrights and trademarks. Customer shall not sell, exchange or transfer the IB Software to others. Customer shall not copy, modify, translate, decompile, reverse engineer, disassemble or reduce to a human readable form, or adapt, the IB Software or use it to create a derivative work, unless authorized in writing by an officer of IB. IB is entitled to immediate injunctive relief for threatened breaches of these undertakings.</p>
                <p> 使用盈透软件的许可：盈透授权客户非排他性的、非转让性的根据本合同的规 定单独使用盈透软件的许可。盈透对其软件和更新版本仍拥有独家所权，包括所有专利、版权或商标。客户不应出售、交换或转让盈透的软件给其他人。除非获得盈透管理人员的书面授权，否则客户不应拷贝、修改、翻译、解码、反向工程、反汇编或减化为人们可读取的形式，或改编盈透软件或使用IB软件创建一个衍生的项目。盈透有权向法庭申请对违反上述承诺的威胁发布禁制令。</p>
                <p> 27. LIMITATION OF LIABILITY AND LIQUIDATED DAMAGES PROVISION: CUSTOMER ACCEPTS THE IB SYSTEM "AS IS", AND WITHOUT WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR USE, PURPOSE OR APPLICATION; TIMELINESS; FREEDOM FROM INTERRUPTION; OR ANY IMPLIED WARRANTIES ARISING FROM TRADE USAGE, COURSE OF DEALING OR COURSE OF PERFORMANCE. UNDER NO CIRCUMSTANCES SHALL IB BE LIABLE FOR ANY PUNITIVE, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL LOSS OR DAMAGES, INCLUDING LOSS OF BUSINESS, PROFITS ORGOODWILL. IB SHALL NOT BE LIABLE TO CUSTOMER BY REASON OF DELAYS OR INTERRUPTIONS OF SERVICE OR TRANSMISSIONS, OR FAILURES OF PERFORMANCE OF THE IB SYSTEM, REGARDLESS OF CAUSE, INCLUDING, BUT NOT LIMITED TO, THOSE CAUSED BY HARDWARE OR SOFTWARE MALFUNCTION; GOVERNMENTAL, EXCHANGE OR OTHER REGULATORY ACTION; ACTS OF GOD; WAR, TERRORISM, OR IB'S INTENTIONAL ACTS. CUSTOMER RECOGNIZES THAT THERE MAY BE DELAYS OR INTERRUPTIONS IN THE USE OF THE IB SYSTEM, INCLUDING, FOR EXAMPLE, THOSE CAUSED INTENTIONALLY BY IB FOR PURPOSES OF SERVICING THE IB SYSTEM. IN NO EVENT SHALL IB'S LIABILITY, REGARDLESS OF THE FORM OF ACTION AND DAMAGES SUFFERED BY CUSTOMER, EXCEED THE HIGHEST TOTAL MONTHLY COMMISSIONS PAID BY CUSTOMER TO IB OVER THE 6 MONTHS PRIOR TO ANY INCIDENT.</p>
                <p> 有限责任与违约赔偿金规定：客户接受盈透系统“现有的”状况，无明示或暗示的担保、包括但不限于对适销性或某特定用途的适应性的担保、应用目的的担保、及时性、免于中断的担保，或任何暗含的由交易使用、交易过程或履行过程所引起的担保。在任何情况下，盈透对任何惩罚性的、间接的、偶然的、特殊的或连带的损失或损害均不承担责任，包括业务、收益或商誉的损失。盈透对由于服务的延迟、中断或传送、或 操作盈透的系统故障不承担责任，无论是何原因，包括但不限于那些由硬件或软件故障 所引起的故障；政府的、交易所的或其它监管机构的行动所引起的；天灾、战争、恐怖 主义或盈透的有意行动。客户确认在使用盈透系统时可能出现延迟或中断情况，例如包括那些由盈透有意为维护其系统所导致的上述问题在任何情况下，无论采取何种行动，无论客户遭受何种损失，盈透的责任不应超过发生的任何事故前六个月内由客户支付给盈透的最高的月佣金总额。</p>
                <p> 28. Customer Must Maintain Alternative Trading Arrangements: Computer-based systems such as those used by IB are inherently vulnerable to disruption, delay or failure. CUSTOMER MUST MAINTAIN ALTERNATIVE TRADING ARRANGEMENTS IN ADDITION TO CUSTOMER'S IB ACCOUNT FOR EXECUTION OF CUSTOMER'S ORDERS IN THE EVENT THAT THE IB SYSTEM IS UNAVAILABLE. By signing this Agreement, Customer represents that Customer maintains alternative trading arrangements.</p>
                <p> 客户必须保持可选择的交易安排：基于计算机的系统，例如盈透使用的系统，从本质上说容易中断、延迟或发生故障。除了客户的盈透账户外，客户必须做出可选择的交易安排以便在盈透系统无法使用时执行客户的定单ã 通过签署本合同，客户表示其已做出可选择的交易安排。</p>
                <p> 29. IB and Its Affiliates: A copy of IB's audited financial statements shall be posted on the IB website and, upon request, mailed to Customer. Customers shall rely only on the financial condition of IB, and not on its affiliates, which are not liable for IB's acts and omissions.</p>
                <p>盈透及其分支机构：经过审计的盈透财务报表应公布在盈透的网站上，并可在客户要求下邮寄给客户。客户应仅依据盈透而非其分支机构的财务状况，分支机构对盈透的行为与失误不负有责任。</p>
                <p> 30. DISCLOSURE STATEMENT: THIS STATEMENT IS FURNISHED TO YOU BECAUSE RULE 190.10(c) OF THE COMMODITY FUTURES TRADING COMMISSION REQUIRES IT FOR REASONS OF FAIR NOTICE UNRELATED TO IB'S CURRENT FINANCIAL CONDITION: (A) YOU SHOULD KNOW THAT IN THE UNLIKELY EVENT OF THIS COMPANY'S BANKRUPTCY, PROPERTY, INCLUDING PROPERTY SPECIFICALLY TRACEABLE TO YOU, WILL BE RETURNED, TRANSFERRED OR DISTRIBUTED TO YOU, OR ON YOUR BEHALF, ONLY TO THE EXTENT OF YOUR PRO RATA SHARE OF ALL PROPERTY AVAILABLE FOR DISTRIBUTION TO CUSTOMERS; (B) NOTICE CONCERNING THE TERMS FOR THE RETURN OF SPECIFICALLY IDENTIFIABLE PROPERTY WILL BE MADE BY PUBLICATION IN A NEWSPAPER OF GENERAL CIRCULATION; (C) THE COMMISSION'S REGULATIONS CONCERNING BANKRUPTCIES OF COMMODITY BROKERS CAN BE FOUND AT TITLE 17 OF THE CODE OF FEDERAL REGULATIONS PART 190.</p>
                <p> 披露声明：鉴于商品期货贸易委员会规则190.10(c)要求的与盈透当前的财政状况无关的公平通知原因，特对客户发表以下声明：(A)您应当知悉万一本公司破产，资产（包括客户可明确追查的资产）将被归还、转移或分配给您，或您的代表，按客户资产的比例分摊可分配的资产数额；(B)对于归还明确可识别产的通知将通过一般流通的报纸发行公告。(C)委员会关于商品经纪人破产的监管条例列于联邦法规条例190第17法令。</p>
                <p> 31. Consent To Accept Electronic Records And Communications </p>
                <p>IB provides electronic trade confirmations, account statements, tax information and other Customer records and communications (collectively, "Records and Communications") in electronic form. Electronic Records and Communications may be sent to Customer's Trader Workstation ("TWS") or to Customer's e-mail address, or for security purposes may be posted on the IB website and customer will need to log in and retrieve the Communication. By entering into this Agreement, Customer consents to the receipt of electronic Records and Communications. Such consent will apply on an ongoing basis and for every tax year unless withdrawn by Customer. Customer may withdraw such consent at any time by providing electronic notice to IB through the IB website. If Customer withdraws such consent, IB will provide required tax documents in paper form upon request by telephone or via the IB website. However, IB reserves the right to require Customer to close Customer's account.</p>
                <p>盈透通过电子形式提供电子交易确认书、账单、税务信息与其它客户记录与通信联 系，(以下简称" 电子记录与通信联系" )。电子记录与通信联系可发送到客户的交易平台或发送到客户的电子邮件地址或为了安全起见公布在盈透的网站上，同时通知 客户登录并检索上述通信联系。通过签署本合同，客户同意接收电子记录与通信联 系。除非客户收回其同意，否则上述同意持续适用，并适用于每个税务年度。客户可在任何时候通过盈透的网站以电子方式通知盈透收回其同意。如果客户收回其同意，则当客户通过电话或通过盈透网站要求时，盈透应提供纸质形式的税务文件。 但是，盈透保留要求客户关闭其账户的权利。 In order to trade using the IB TWS, and to receive Records and Communications through the TWS, there are certain system hardware and software requirements, which are described on the IB website at www.interactivebrokers.com. Since these requirements may change, Customer must periodically refer to the IB website for current system requirements. To receive electronic mail from IB, Customer is responsible for maintaining a valid Internet e-mail address and software allowing customer to read, send and receive e-mail. Customer must notify IB immediately of a change in Customer's e-mail address by using those procedures to change a Customer e-mail address that may be available on the IB website.</p>
                <p>为了使用盈透的交易平台（“TWS”）进行交易，和通过交易平台接收电子记录与通信联系，对系统软件和硬件有一些要求，这些要求在盈透的网站 www.interactivebrokers.com进行说明。由于上述要求可能发生变化，客户必须定期访问盈透网站，了解当前的系统要求。要想收到盈透的电子邮件，客户负责维护一个有效的因特网电子邮件地址和软件，以允许客户阅读、发送、接收电子邮件。 当客户邮件地址变化时，客户必须通过这些程序立刻通知盈透，以便更改盈透网站上的客户邮件地址。</p>
                <p> 32. Miscellaneous:</p>
                <p> 其他：</p>
                <p> A. This Agreement is governed by the laws of the State of New York, without giving effect to conflict of laws provisions. Courts of New York have exclusive jurisdiction over disputes relating to this Agreement, except when arbitration is provided. IN ALL JUDICIAL ACTIONS, ARBITRATIONS OR DISPUTE RESOLUTION METHODS, THE PARTIES WAIVE ANY RIGHT TO PUNITIVE DAMAGES.</p>
                <p>本合同受美国康涅狄格州法律的管辖，与法律规定相抵触的条款不予生效。康涅狄格州的法院对与本合同有关的争议具有专有管辖权。除了有仲裁规定时例外。在所有司法行为、仲裁或争议的解决方法中，合同各方放弃任何的损害性赔偿的权利。</p>
                <p> B. Customer agrees to the provision of this Agreement in English and represents that Customer understands its terms and conditions. This Agreement contains the entire agreement between the parties, who have made no other representations or warranties. If any provision of this Agreement is unenforceable, it shall not invalidate other provisions. Failure of IB to enforce any term or condition of this Agreement is not a waiver of the term/ condition.</p>
                <p> 客户同意本合同的规定以英文书写且表示客户理解本合同的条款。本合同包括合同双方之间的完整合同，除此以外，合同双方不做出其它陈述或担保。如本合同中的任何规定不可执行，不应影响其它规定的效力。盈透未能履行本合同的任何条款不可视为其对合同条款的放弃。</p>
                <p> C. Customer consents to recording of all telephone conversations. Customer acknowledges the IBG Privacy Statement and consents to collection/use of Customer information as described therein.</p>
                <p> 客户同意录音所有电话内容。客户确认盈透隐私声明且同意根据其规定收集／使用客户信息。</p>
                <p> D. Customer may not assign or transfer any rights or obligations hereunder without the prior written consent of IB. Upon notice to Customer IB may assign this Agreement to another broker-dealer or futures commission merchant. This Agreement shall inure to the benefit of IB's successors and assigns. IB may terminate this Agreement or its services to Customer at any time. Customer may close its account upon notice to IB electronically through the IB website, but only after all positions are closed and all other requirements specified on the IB website regarding account closure are satisfied.</p>
                <p> 如无盈透的事先书面同意，客户不可出让或转让本合同下的任何权利或义务。在向客户发出通知后，盈透可将本合同转让给另一经纪人－交易商或期货经纪商。本合同应保证盈透继承者或受让人的利益。盈透可在任何时候终止本合同或向客户提供服务。客户可通过盈透的网站以电子方式通知盈透后关闭其账户，但只有在所有仓位清仓后，并满足盈透网站上规定的关闭账户的所有其它要求。</p>
                <p> E. Customer authorizes IB, directly or through third parties, to make any inquiries that IB considers necessary to conduct business with Customer. This may include ordering a credit report and performing other credit checks in the event of any default or breach of the obligations herein by Customer, or verifying the information Customer provides against third party databases. Any information obtained is maintained in accordance with the Interactive Brokers Group Privacy Statement.</p>
                <p>客户直接或经第三方授权盈透就其认为其在与客户进行商业活动时所必须的信息询问客户。询问可包括在客户发生任何违约或违法本协议义务时而索取的信用报 告及其它信用检查，或核对客户向第三方数据库提供的信息。盈透获取的信息将遵循盈透集团隐私声明保护。</p>
                <p> 33. Mandatory Arbitration:</p>
                <p> 强制性仲裁：</p>
                <p> A. This agreement contains a pre-dispute arbitration clause. By signing an arbitration agreement the parties agree as follows:</p>
                <p> • ALL PARTIES TO THIS AGREEMENT ARE GIVING UP THE RIGHT TO SUE EACH OTHER IN COURT, INCLUDING THE RIGHT TO A TRIAL BY JURY, EXCEPT AS PROVIDED BY THE RULES OF THE ARBITRATION FORUM IN WHICH A CLAIM IS FILED.</p>
                <p> • ARBITRATION AWARDS ARE GENERALLY FINAL AND BINDING; A PARTY'S ABILITY TO HAVE A COURT REVERSE OR MODIFY AN ARBITRATION AWARD IS VERY LIMITED.</p>
                <p> • THE ABILITY OF THE PARTIES TO OBTAIN DOCUMENTS, WITNESS STATEMENTS AND OTHER DISCOVERY IS GENERALLY MORE LIMITED IN ARBITRATION THAN IN COURT PROCEEDINGS.</p>
                <p> • THE ARBITRATORS DO NOT HAVE TO EXPLAIN THE REASON(S) FOR THEIR AWARD. UNLESS, IN AN ELIGIBLE CASE, A JOINT REQUEST FOR AN EXPLAINED DECISION HAS BEEN SUBMITTED BY ALL PARTIES TO THE PANEL AT LEAST 20 DAYS PRIOR TO THE FIRST SCHEDULED HEARING DATE.</p>
                <p> • THE PANEL OF ARBITRATORS WILL TYPICALLY INCLUDE A MINORITY OF ARBITRATORS WHO WERE OR ARE AFFILIATED WITH THE SECURITIES INDUSTRY.</p>
                <p> • THE RULES OF SOME ARBITRATION FORUMS MAY IMPOSE TIME LIMITS FOR BRINGING A CLAIM IN ARBITRATION.</p>
                <p> • IN SOME CASES, A CLAIM THAT IS INELIGIBLE FOR ARBITRATION MAY BE BROUGHT IN COURT.</p>
                <p> • THE RULES OF THE ARBITRATION FORUM IN WHICH THE CLAIM IS FILED, AND ANY AMENDMENTS THERETO, SHALL BE INCORPORATED INTO THIS AGREEMENT.</p>
                <p> A. 该合同包含预争议仲裁条款。签署仲裁协议代表各方同意以下条款：</p>
                <p> • 本合同的所有各方均放弃将另一方起诉至法庭的权利，包括由陪审团进行审判的权利，除非接受索赔的仲裁机构另有规定。</p>
                <p> • 仲裁判决一般来说是终局且必须遵守的；一方让法庭推翻或修改仲裁判决的能力是非常有限的。</p>
                <p> • 合同各方在仲裁中获得文件、证人证言与其它证据调查程序的能力通常比在法庭审理程序中更为有限。</p>
                <p> • 仲裁人员不必解释做出仲裁裁决的原因。</p>
                <p> • 除非具有合理的解释，各方至少在首次听证日前不少于20天向陪审员小组提交联名请求，要求审判决定附带解释。</p>
                <p> • 仲裁团内通常会包括少数以前或现在与证券行业有关的仲裁员。</p>
                <p> • 某些仲裁委员会的仲裁规则可能对仲裁中的权利要求施加时间限制。</p>
                <p> • 在一些案例中，对于不适合于仲裁的权利要求可向法院提起诉讼。</p>
                <p> • 接受索赔的仲裁委员会的规则和任何相关修订应纳入本合同。</p>
                <p> B. Customer agrees that any controversy, dispute, claim, or grievance between IB, any IB affiliate or any of their shareholders, officers, directors employees, associates, or agents, on the one hand, andCustomer or, if applicable, Customer's shareholders, officers, directors employees, associates, or agents on the other hand, arising out of, or relating to, this Agreement, or any account(s) established hereunder in which securities may be traded; any transactions therein; any transactions between IB and Customer; any provision of the Customer Agreement or any other agreement between IB and Customer; or any breach of such transactions or agreements, shall be resolved by arbitration, in accordance with the rules then prevailing of any one of the following: (a) The Financial Industry Regulatory Authority; or (b) any other exchange of which IB is a member, as the true claimant-in- interest may elect. If Customer is the claimant-in-interest and has not selected an arbitration forum within ten days of providing notice of Customer's intent to arbitrate, IB shall select the forum. The award of the arbitrators, or a majority of them, shall be final, and judgment upon the award rendered may be entered in any court, state or federal, having jurisdiction.</p>
                <p> B．客户同意，当作为一方的盈透、任何盈透分支机构或其任何股东、官员、董事雇员、伙伴、或代理与作为另一方的客户、或如适用，其股东、官员、董事雇员、伙伴、或代理之间因为或关于本合同或根据本合同所设立的用于交易证券的任何帐户（证券交易帐户）；其中的任何交易；盈透与客户间完成的任何交易；客户合同或盈透与客户签 订的任何其他合同的任何规定；或违反任何交易或合同等而发生任何争议、纠纷、索赔或 不满时，这些争议、纠纷、索赔或不满应通过下列任何其中一家仲裁组织的主要规定仲裁 解决：(a) 美国仲裁协会；(b) 美国金融业监管局；或(c)盈透为其成员的任何其它交易所， 由具体的权利要求请求人选择决定。如客户为权利人，但客户在其发出仲裁意向通知后十天内并未选择任何仲裁庭，则盈透应选择仲裁庭。仲裁员或多数仲裁员做出的裁决应为终局的，仲裁做出的判决可记录在具有管辖权的任何州或联邦法庭。</p>
                <p> C. No person shall bring a putative or certified class action to arbitration, nor seek to enforce any pre- dispute arbitration agreement against any person who has initiated in court a putative class action; or who is a member of a putative class who has not opted out of the class with respect to any claims encompassed by the putative class action until:</p>
                <p> • the class certification is denied; or</p>
                <p> • the class is decertified; or</p>
                <p> • the customer is excluded from the class by the court. Such forbearance to enforce an agreement to arbitrate shall not constitute a waiver of any rights under this Agreement except to the extent stated herein.</p>
                <p> C.任何人均不得将一项法院可能判决或已经判决的集体诉讼提交仲裁，也不得对已认定向 法院提起集体诉讼的人士，或已经是集体诉讼中一员且未因集体诉讼所包括的任何索赔而退出的人士，强迫执行预争议仲裁合同，除非：</p>
                <p> • 集体诉讼被拒绝，或</p>
                <p> • 该集体诉讼的法院受理被取消；或</p>
                <p> • 法院已将该客户排除在该集体诉讼之外。除于此说明外，强制以仲裁方式解决合同纠纷的行为并不构成放弃本合同内的任何权利。</p>
                <p> THIS AGREEMENT CONTAINS A PRE-DISPUTE ARBITRATION CLAUSE IN PARAGRAPH 33. BY SIGNING THIS AGREEMENT I ACKNOWLEDGE THAT THIS AGREEMENT CONTAINS A PRE-DISPUTE ARBITRATION CLAUSE AND THAT I HAVE RECEIVED, READ AND UNDERSTOOD THE TERMS THEREOF.</p>
                <p> 本合同在第33段中包含一条预争议仲裁条款。签署合同表示本人知晓合同中包含一条预争议仲 裁条款，且本人已收到、阅读并理解上述条款。</p>
                <p> 声明：本翻译文件仅以提供方便为目的。IBLLC 并不保证或确保翻译的完整性或正确性。在英文原文与中文翻译本不一致的情况下，应以英文版为准。</p>
            </div>
            <section class="declare-container">
                <section class="declare-item">
                    <span @click="setDeclare('我不同意')">我不同意</span>
                </section>
                <section class="declare-item">
                    <span @click="setDeclare('我同意')">我同意</span>
                </section>
            </section>
        </section>
    </div>
</template>
<script>
import headTop from '../../../components/header/head'
import BScroll from 'better-scroll'
import {
    mapState,
    mapActions
} from 'vuex'
export default {
    components: {
        headTop
    },

    data() {
        return {
            userName: ''
        }
    },


    created() {
        this.initData();
    },

    methods: {
        initData() {},

        setDeclare(declare) {
            this.$store.state.declare_customer = declare;
            this.$router.go(-1);
        }
    }

}
</script>
<style lang="scss" scoped>
@import '../../../style/mixin';
.menu {
    padding-top: $containerTop;
}

.qustion-item {
    padding: 0.5rem 0.5rem 0.5rem 0.5rem;
    padding-bottom: 3rem;
    p {
        margin-top: 0.2rem;
        margin-bottom: 0.5rem;
        @include sc(.6rem, $fontGreyColor);
    }
    .title {
        @include sc(.75rem, $fontColor);
    }
}

.declare-container {
    position: fixed;
    display: flex;
    width: 100%;
    bottom: 0;
    padding-bottom: .5rem;
    padding-top: .3rem;
    background-color: $grey;
    .declare-item {
        text-align: center;
        flex: 1;
        span {
            background-color: $grey3;
            text-align: center;
            padding: 0.2rem 0.4rem;
            @include sc(.6rem, $fontColor);
        }
    }
    .declare-item:last-child {
        span {
            background-color: $blue;
        }
    }
}
</style>
